# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Sample configuration for the landing page theme
# Replace these values with your own!

baseurl: "" # the subpath of your site, e.g. /repo-name

name: Alexandre Koroneos
# email: mail@alexkoro.com
tagline: "Computer Science @ Humboldt University of Berlin"
# description: "A longer description about you or your site."
github_username: axkoro
linkedin_username: alexandre-koroneos
# resume_url: /assets/resume.pdf
# twitter_username: your-twitter
# blog_url: https://yourblog.com

# Portfolio projects
portfolio:
  - title: "graph-impute"
    description: "A tool that predicts and adds missing information in network data"
    image_url: /assets/projects/graph-impute.png
    # demo_url: https://demo1.com
    github_url: https://github.com/axkoro/graph-impute
    
  - title: "Statistics & Data Science"
    description: "Statistical analysis projects including Naive Bayes text classification, multivariate regression, and hypothesis testing on real-world datasets"
    image_url: /assets/projects/naive-bayes.jpg
    # demo_url: https://demo3.com
    github_url: https://github.com/axkoro/sds
    
  - title: "Scientific Computing"
    description: "Numerical algorithms and parallel computing with MPI including sparse matrix operations, linear solvers, and distributed sorting"
    image_url: /assets/projects/scicomp.jpg
    # demo_url: https://demo4.com
    github_url: https://github.com/axkoro/scicomp

  - title: "OS Fundamentals"
    description: "Low-level systems programming exercises including bootloader, memory allocator, and a simple shell"
    image_url: /assets/projects/shell.png
    # demo_url: https://demo2.com
    github_url: https://github.com/axkoro/os-exercises

# Build settings
plugins:
  - jekyll-feed
